working_directory: ../microservice_int/
pace:
  REFRESH: 180
  RUNNING: 600
  CHECK: 600
  MATCHING: 60
  PRICE_UPDATE: 600
session:
  binance:
    config_file: ../microservice_aws3_int/config/config_pair_session_binbitget.json
    config_position_matching_file: ../microservice_aws3_int/config/config_position_matching.json
    check_running: true
    check_realpose: false
    check_pnl: false
    session_file: ../microservice_aws3_int/output_bin/session.log


