working_directory: ~/Python/github/microservice_aws3_int/
pace:
  REFRESH: 180
  RUNNING: 600
  CHECK: 600
  MATCHING: 60
  PRICE_UPDATE: 600
session:
  binance:
    config_file: ~/Python/github/data/ms_algo3/config/session_binance.json
    config_position_matching_file: config/config_position_matching.json 
    check_running: true
    check_realpose: false
    check_pnl: false
    session_file: ~/Python/github/data/ms_algo3/output/binance/session.log


