logs:
  level: INFO
  file: ~/web_processor.log
  backup_count: 5
pace:
  CHECK: 600
  PRICE_UPDATE: 600
session:
  binance:
    config_file: ~/Python/github/data/ms_algo3/config/session_binance.json
    config_position_matching_file: config/config_position_matching.json 
    check_running: true
    check_realpose: false
    check_pnl: false
    session_file: ~/Python/github/data/ms_algo3/output/binance/session.log


